services:
  - type: web
    name: magento-detector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: WEB_CONCURRENCY
        value: 4
      - key: MAX_WORKERS
        value: 4
      - key: TIMEOUT
        value: 30
      - key: KEEP_ALIVE
        value: 2
      - key: MAX_REQUESTS
        value: 1000
      - key: MAX_REQUESTS_JITTER
        value: 100
    scaling:
      minInstances: 1
      maxInstances: 3
    healthCheckPath: /api/health